[build]
  publish = "dist"
  command = "npm run build"
  functions = "lambda-prod"

[context.production.environment]
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.48"
